language: objective-c
osx_image: xcode8.2
xcode_workspace: photoWall.xcworkspace
xcode_scheme: photoWall

script:
  - xcodebuild -scheme photoWall -workspace photoWall.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)